{
  "swagger": "2.0",
  "info": {
    "version": "1",
    "title": "Location History",
    "description": " \n Location hsssistory is data that is sent from the MileApp Field mobile app or sent from API. The location history will be sent regularly from the mobile app if the Start Finish feature is active based on the permission setting at the user's role. There were two types of location history, as stated below:\n  - The first type of location history contains IDs, email, latitude longitude, speed, distance, duration, and timestamp.\n  - The second type is the Start Finish data, for this type the data structure should contain IDs, email, latitude longitude, speed, distance, duration, timestamp, start time, finish time, finish latitude longitude, notes, and data object.\n\n**This collection API will show you how to how to manipulate data of Location History.** \n \n | Field | Type | Format | Description | \n |---|---|---|---|\n | _id | <a href='#introduction-format'>string</a> | *combination of organization id, email, and timestamp* | Unique identifier for the location history<br>that generated by system.<br>**Example**: `634e98098ce07d29474a7e22_example@mile.app_1675224349343`|\n | organizationId | <a href='#introduction-format'>string</a> | *24 characters of hexadecimal* | The identifier for the organization<br>that generated by system.<br>**Example:** `634e98098ce07d29474a7e22`|\n | email | <a href='#introduction-format'>string</a> | *String with Email Format*<br>`example@mile.app` | Worker's email that assigned to the monitored task.<br>**Example**: `example@mile.app` |\n | taskId | <a href='#introduction-format'>string</a> | | The ID of Task.<br>**Example:** `634e98098ce69d29474a7e11` | \n | lat | <a href='#introduction-format'>float</a> | *Float number of Lattitude* | The latitude coordinate position or location of any place on Earth's surface can be determined and described.<br>**Example**: `-6.285618073716509` | \n | lon | <a href='#introduction-format'>float</a> | *Float number of Longitude* | The longitude coordinate position or location of any place on Earth's surface can be determined and described.<br>**Example**: `106.84459308015525` | \n | speed | <a href='#introduction-format'>number</a> |  | The rate of change of position of an object in any direction (in km/h).<br>**Example**: `40` |\n | distance | <a href='#introduction-format'>number</a> |  | The length of the actual path travelled by a moving body between its initial and final positions.<br>**Example**: `50` |\n | duration | <a href='#introduction-format'>number</a> |  | Duration time measured in miliseconds.<br>**Example**: `50` |\n | time | <a href='#introduction-format'>string</a> |  | Auto-generated timestamp of Location History.<br>**Example**: `1675224349343`| \n | startTime | <a href='#introduction-format'>datetime</a> | `Y-m-d H:i:s` |   The time when the start of work was created. Put this payload when the user starts working.<br>**Example:** `2022-10-07 03:00:58`|\n | notes | <a href='#introduction-format'>string</a> |  | Notes are used to add or explain optional information.|\n | finish | <a href='#introduction-format'>object</a> |  | Contains object data when the user has finished working.|\n | &nbsp;&nbsp;&nbsp;.lat | <a href='#introduction-format'>float</a> | *Float number of Lattitude* | The latitude coordinate position or location of any place on Earth's surface can be determined and described.<br>**Example**: `-6.285618073716509` | \n | &nbsp;&nbsp;&nbsp;.lon | <a href='#introduction-format'>float</a> | *Float number of Longitude* | The longitude coordinate position or location of any place on Earth's surface can be determined and described.<br>**Example**: `106.84459308015525` | \n | &nbsp;&nbsp;&nbsp;.finishTime | <a href='#introduction-format'>datetime</a> | `Y-m-d H:i:s` | Time at which the finish of work was created. Put this payload when the user finishes working.<br>**Example:** `2022-10-07 03:00:58`|\n | &nbsp;&nbsp;&nbsp;.notes | <a href='#introduction-format'>string</a> |  | Notes are used to add or explain optional information.|\n | &nbsp;&nbsp;&nbsp;.totalDistance | <a href='#introduction-format'>number</a> |  | The length of the actual path traveled by the user between its initial and final positions.<br>*This is auto-generated when the finish is triggered. *<br>**Example**: `150`|\n | &nbsp;&nbsp;&nbsp;.totalDuration | <a href='#introduction-format'>number</a> |  | Total duration time measured in milliseconds. <br>*This is auto-generated when the finish is triggered.* |\n | data | <a href='#introduction-format'>object</a> |  | This is a free object, you can fill it with any information you need within the object format.<br>**Example:** `{\"temperature\": 31, \"anotherKey\": \"anotherValue\"}` |\n | trackedTime | <a href='#introduction-format'>number</a> |  | Time tracked is the start to finish time distance data in minutes. |\n | createdTime | <a href='#introduction-format'>datetime</a> | `Y-m-d H:i:s` | Time at which the location history is created.<br>**Example:** `2022-10-07 03:00:58`|\n | updatedTime | <a href='#introduction-format'>datetime</a> | `Y-m-d H:i:s` | Time at which the location history is updated.<br>**Example:** `2022-10-07 04:00:58`|\n | deletedTime | <a href='#introduction-format'>datetime</a> | `Y-m-d H:i:s` | Time at which the location history is deleted.<br>**Example:** `2022-10-07 05:00:58`|\n "
  },
  "host": "apiweb.mile.app",
  "basePath": "/api/v3",
  "securityDefinitions": {
    "AccessToken": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    },
    "x-api-key": {
      "type": "apiKey",
      "name": "x-api-key",
      "in": "header"
    }
  },
  "schemes": [
    "https"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/location-histories": {
      "get": {
        "summary": "Read location history",
        "tags": [
          "Location History"
        ],
        "operationId": "getLocationHistory",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "email",
            "in": "query",
            "required": false,
            "type": "string",
            "description": "Worker's email that assigned to the monitored task."
          },
          {
            "name": "taskId",
            "in": "query",
            "required": false,
            "type": "string",
            "description": "The identifier for the task that generated by system. Use <a href='#Task_Task'>GET /tasks API</a> to get the list of Task IDs.<br>**Example:** `621dd813eb3ebf16b94d6969`"
          },
          {
            "name": "limit",
            "in": "query",
            "required": false,
            "type": "string",
            "description": "Limit of records list.<br>**Example:** `10`.<br>**Default:** `20`"
          },
          {
            "name": "page",
            "in": "query",
            "required": false,
            "type": "integer",
            "format": "int32",
            "description": "Pagination of records list.<br>**Example:** `2`.<br>**Default:** `0`"
          },
          {
            "name": "sortOrder",
            "in": "query",
            "required": false,
            "type": "string",
            "description": "sortOrder is to decide ascending or descending order by `createdTime` <br>**Example:** `asc` or `desc`.<br>**Default:** `desc`"
          },
          {
            "name": "timeBy",
            "in": "query",
            "required": false,
            "type": "string",
            "description": "date time selector.<br>**Example:** `createdTime`"
          },
          {
            "name": "timeFrom",
            "in": "query",
            "required": false,
            "type": "string",
            "description": "date time selector to select timeBy from.<br>**Example:** `2023-00-01 00:00:00`"
          },
          {
            "name": "timeTo",
            "in": "query",
            "required": false,
            "type": "string",
            "description": "date time selector to select timeBy to.<br>**Example:** `2023-00-10 00:00:00`"
          },
          {
            "name": "startFinish",
            "in": "query",
            "required": false,
            "type": "string",
            "description": "when the value is `true` the start finish record will be show, if the value is `false` it only displays the location history record."
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema":{
              "type": "object",
              "title": "NetworkCreateResponse",
              "properties": {
                "status": {
                  "description": "Status of response.",
                  "type": "boolean"
                },
                "message": {
                  "description": "Message of API response.",
                  "type": "string"
                },
                "tasks": {
                  "description": "Detail of object location history.",
                  "type": "object"
                }
              },
              "example": {
                  "status": true,
                  "message": "Success",
                  "tasks": {
                    "current_page": 1,
                    "data": [
                      {
                        "email": "example@mile.app",
                        "taskId": "634e98098ce69d29474a7e11",
                        "speed": 40,
                        "distance": 50,
                        "duration": 50,
                        "lat": -6.1771046,
                        "lon": 106.9240199,
                        "_id": "634e98098ce07d29474a7e22_example@mile.app_1675224349343",
                        "time": 1675224349343,
                        "organizationId": "634e98098ce07d29474a7e22",
                        "createdTime": "2022-10-07 03:00:58",
                        "updatedTime": "2022-10-07 04:00:58"
                      },
                      {
                        "_id": "64a696536d01ea0d503db772",
                        "email": "example@mile.app",
                        "lat": -6.23239438813826,
                        "lon": 106.82152618097032,
                        "speed": 0,
                        "distance": 0,
                        "duration": 0,
                        "startTime": "2023-07-06 10:23:00",
                        "notes": null,
                        "createdTime": "2023-07-06 10:24:19",
                        "taskId": "",
                        "time": 1688639059872,
                        "organizationId": "6488344e8db84c3a511f62b2",
                        "finish": {
                          "lat": -6.296958793290206,
                          "lon": 106.7858189729966,
                          "finishTime": "2023-07-06 11:23:00",
                          "notes": null,
                          "totalDuration": 60,
                          "totalDistance": 24
                        },
                        "updatedTime": "2023-07-06 10:53:36",
                        "trackedTime": 60
                      }
                    ],
                    "first_page_url": "http://apiweb.mile.app/api/location-histories?limit=20&fields=email%2CtaskId%2Clon%2Clat&email=example%40mile.app&sortBy=createdTime&sortOrder=desc&page=1",
                    "from": 1,
                    "last_page": 1,
                    "last_page_url": "http://apiweb.mile.app/api/location-histories?limit=20&fields=email%2CtaskId%2Clon%2Clat&email=example%40mile.app&&sortBy=createdTime&sortOrder=desc&page=1",
                    "links": [
                      {
                        "url": null,
                        "label": "&laquo; Previous",
                        "active": false
                      },
                      {
                        "url": "http://apiweb.mile.app/api/location-histories?limit=20&fields=email%2CtaskId%2Clon%2Clat&email=example%40mile.app&&sortBy=createdTime&sortOrder=desc&page=1",
                        "label": "1",
                        "active": true
                      },
                      {
                        "url": null,
                        "label": "Next &raquo;",
                        "active": false
                      }
                    ],
                    "next_page_url": null,
                    "path": "http://apiweb.mile.app/api/location-histories",
                    "per_page": 20,
                    "prev_page_url": null,
                    "to": 2,
                    "total": 2
                  }
              }
            },
            "headers": {}
          }
        },
        "security": [
          {
            "AccessToken": [],
            "x-api-key": []
          }
        ]
      }
    },
    "/location-history": {
      "post": {
        "summary": "Create location history",
        "description": "Location history data is transmitted from the MileApp Field mobile app or through the API. This data is sent regularly from the mobile app if the 'Start Finish' feature is active, based on the permission settings associated with the user's role.<br>There are two primary types of location history data:<br><br>**1. Standard Location History**<br>This type of location history includes essential information such as IDs, email, latitude, longitude, speed, distance, duration, and timestamp.<br><br>**2. Start Finish Location History**<br>For this type of location history, the data structure expands to include additional details:<br>- IDs<br>- Email<br>- Latitude<br>- Longitude<br>- Speed<br>- Distance<br>- Duration<br>- Timestamp<br>- Start Time<br>- Finish Time<br>- Finish Latitude<br>- Finish Longitude<br>- Notes<br>- Data Object<br><br>Location history data plays a crucial role in the MileApp web application. It is primarily used within the 'Task/Tracking' menu to monitor field user-assigned tasks on a map. This functionality allows users to track the journey of field personnel in real-time, providing valuable insights into their movements and progress.",
        "tags": [
          "Location History"
        ],
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/postRequestLocHistory"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Success",
            "schema":{
              "$ref": "#/definitions/ApiResponse"
            },
            "examples": {
              "application/json": {
                "status": true,
                "message": "Success",
                "location_history": {
                  "email": "example@mile.app",
                  "taskId": "634e98098ce69d29474a7e11",
                  "speed": 40,
                  "distance": 50,
                  "duration": 50,
                  "lat": -6.1771046,
                  "lon": 106.9240199,
                  "_id": "634e98098ce07d29474a7e22_example@mile.app_1675224349343",
                  "time": 1675224349343,
                  "organizationId": "634e98098ce07d29474a7e22",
                  "createdTime": "2022-10-07 03:00:58",
                  "updatedTime": "2022-10-07 04:00:58"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "schema":{
              "$ref": "#/definitions/ErrorResponse"
            },
            "examples": {
              "application/json": {
                "status": false,
                "message": "message",
                "failedCode": "lochi-001"
              }
            }
          }
        },
        "security": [
          {
            "AccessToken": [],
            "x-api-key": []
          }
        ]
      },
      "put": {
        "summary": "Update location history by email & createdTime",
        "tags": [
          "Location History"
        ],
        "operationId": "putLocationHistory",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/putRequestLocHistory"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema":{
              "$ref": "#/definitions/ApiResponse"
            },
            "examples": {
              "application/json": {
                "status": true,
                "message": "Success",
                "location_history": {
                  "email": "example@mile.app",
                  "taskId": "634e98098ce69d29474a7e11",
                  "speed": 40,
                  "distance": 50,
                  "duration": 50,
                  "lat": -6.1771046,
                  "lon": 106.9240199,
                  "_id": "634e98098ce07d29474a7e22_example@mile.app_1675224349343",
                  "time": 1675224349343,
                  "organizationId": "634e98098ce07d29474a7e22",
                  "createdTime": "2022-10-07 03:00:58",
                  "updatedTime": "2022-10-07 04:00:58"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "schema":{
              "$ref": "#/definitions/ErrorResponse"
            },
            "examples": {
              "application/json": {
                "status": false,
                "message": "message",
                "failedCode": "lochi-001"
              }
            }
          }
        },
        "security": [
          {
            "AccessToken": [],
            "x-api-key": []
          }
        ]
      }
    },
    "/location-history/bulk": {
      "post": {
        "summary": "Bulk create location history",
        "description": "This API enables mobile devices to create multiple location history entries in bulk. This feature is particularly useful when users are in offline mode and need to store location data locally, syncing it with the server when they regain internet connectivity. The request body should contain a single field location_histories, which is a list of location history entries. Maximum Limit: You can submit a maximum of 1000 location history entries in a single request. Each entry is represented as an object with the following fields:",
        "tags": [
          "Location History"
        ],
        "operationId": "postBulkLocationHistories",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/postBulkRequestLocHistory"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "",
            "schema":{
              "$ref": "#/definitions/BulkResponse"
            },
            "examples": {
              "application/json": {
                "success": 2,
                "failed": 0,
                "tasks": [
                  {
                    "status": true,
                    "message": "Success",
                    "_id": "634e98098ce07d29474a7e22_example@mile.app_1675224349343"
                  },
                  {
                    "status": true,
                    "message": "Success",
                    "_id": "634e98098ce07d29474a7e22_example@mile.app_1675224349578"
                  }
                ]
              }
            },
            "headers": {}
          },
          "400": {
            "description": "Bad Request",
            "schema":{
              "$ref": "#/definitions/ErrorResponse"
            },
            "examples": {
              "application/json": {
                "status": false,
                "message": "message",
                "failedCode": "lochi-001"
              }
            }
          }
        },
        "security": [
          {
            "AccessToken": [],
            "x-api-key": []
          }
        ]
      }
    },
    "/location-history/{loc_history_id}": {
      "get": {
        "summary": "Read location history by ID",
        "tags": [
          "Location History"
        ],
        "operationId": "getLocationHistorybyid",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "loc_history_id",
            "in": "path",
            "required": true,
            "type": "string",
            "description": "Unique identifier for the location history<br>that generated by system.<br>**Example**: `634e98098ce07d29474a7e22_example@mile.app_1675224349343`"
          }
        ],
        "responses": {

          "200": {
            "description": "Success",
            "schema":{
              "$ref": "#/definitions/ApiResponse"
            },
            "examples": {
              "application/json": {
                "status": true,
                "message": "Success",
                "location_history": {
                  "email": "example@mile.app",
                  "taskId": "634e98098ce69d29474a7e11",
                  "speed": 40,
                  "distance": 50,
                  "duration": 50,
                  "lat": -6.1771046,
                  "lon": 106.9240199,
                  "_id": "634e98098ce07d29474a7e22_example@mile.app_1675224349343",
                  "time": 1675224349343,
                  "organizationId": "634e98098ce07d29474a7e22",
                  "createdTime": "2022-10-07 03:00:58",
                  "updatedTime": "2022-10-07 04:00:58"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "schema":{
              "$ref": "#/definitions/ErrorResponse"
            },
            "examples": {
              "application/json": {
                "status": false,
                "message": "Location history not found",
                "failedCode": "lochi-033"
              }
            }
          }
        
        },
        "security": [
          {
            "AccessToken": [],
            "x-api-key": []
          }
        ]
      },
      "patch": {
        "summary": "Update partially location history by ID",
        "tags": [
          "Location History"
        ],
        "operationId": "patchLocationHistory",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "loc_history_id",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/patchRequestLocHistory"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema":{
              "$ref": "#/definitions/ApiResponse"
            },
            "examples": {
              "application/json": {
                "status": true,
                "message": "Data has been updated successfully.",
                "location_history": {
                  "email": "example@mile.app",
                  "taskId": "634e98098ce69d29474a7e11",
                  "speed": 40,
                  "distance": 50,
                  "duration": 50,
                  "lat": -6.1771046,
                  "lon": 106.9240199,
                  "_id": "634e98098ce07d29474a7e22_example@mile.app_1675224349343",
                  "time": 1675224349343,
                  "organizationId": "634e98098ce07d29474a7e22",
                  "createdTime": "2022-10-07 03:00:58",
                  "updatedTime": "2022-10-07 04:00:58"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "schema":{
              "$ref": "#/definitions/ErrorResponse"
            },
            "examples": {
              "application/json": {
                "status": false,
                "message": "message",
                "failedCode": "lochi-001"
              }
            }
          }
        },
        "security": [
          {
            "AccessToken": [],
            "x-api-key": []
          }
        ]
      },
      "put": {
        "summary": "Update location history by ID",
        "tags": [
          "Location History"
        ],
        "operationId": "putLocationHistoryById",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/putRequestLocHistory"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema":{
              "$ref": "#/definitions/ApiResponse"
            },
            "examples": {
              "application/json": {
                "status": true,
                "message": "Data has been updated successfully.",
                "location_history": {
                  "email": "example@mile.app",
                  "taskId": "634e98098ce69d29474a7e11",
                  "speed": 40,
                  "distance": 50,
                  "duration": 50,
                  "lat": -6.1771046,
                  "lon": 106.9240199,
                  "_id": "634e98098ce07d29474a7e22_example@mile.app_1675224349343",
                  "time": 1675224349343,
                  "organizationId": "634e98098ce07d29474a7e22",
                  "createdTime": "2022-10-07 03:00:58",
                  "updatedTime": "2022-10-07 04:00:58"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "schema":{
              "$ref": "#/definitions/ErrorResponse"
            },
            "examples": {
              "application/json": {
                "status": false,
                "message": "message",
                "failedCode": "lochi-001"
              }
            }
          }
        
        },
        "security": [
          {
            "AccessToken": [],
            "x-api-key": []
          }
        ]
      },
      "delete": {
        "summary": "Delete location history by ID",
        "tags": [
          "Location History"
        ],
        "operationId": "deleteLocationHistorybyid",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "loc_history_id",
            "in": "path",
            "required": true,
            "type": "string",
            "description": "Unique identifier for the location history<br>that generated by system.<br>**Example**: `634e98098ce07d29474a7e22_example@mile.app_1675224349343`"
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/deleteRequestLocHistory"
            }
          }
        ],
        "responses": {

          "200": {
            "description": "Success",
            "schema":{
              "$ref": "#/definitions/ApiResponse"
            },
            "examples": {
              "application/json": {
                "status": true,
                "message": "Data has been updated successfully.",
                "location_history": {
                  "email": "example@mile.app",
                  "taskId": "634e98098ce69d29474a7e11",
                  "speed": 40,
                  "distance": 50,
                  "duration": 50,
                  "lat": -6.1771046,
                  "lon": 106.9240199,
                  "_id": "634e98098ce07d29474a7e22_example@mile.app_1675224349343",
                  "time": 1675224349343,
                  "organizationId": "634e98098ce07d29474a7e22",
                  "createdTime": "2022-10-07 03:00:58",
                  "updatedTime": "2022-10-07 04:00:58"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "schema":{
              "$ref": "#/definitions/ErrorResponse"
            },
            "examples": {
              "application/json": {
                "status": false,
                "message": "message",
                "failedCode": "lochi-001"
              }
            }
          }
        
        },
        "security": [
          {
            "AccessToken": [],
            "x-api-key": []
          }
        ]
      }
    },
    "/location-history/recalculate-distance": {
      "post": {
        "summary": "Recalculate distance location history",
        "description": "This API enables for triggered recalculate distance of location history",
        "tags": [
          "Location History"
        ],
        "operationId": "recalculateDistance",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/PostRecalculate"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema":{
              "$ref": "#/definitions/RecalculateResponse"
            },
            "examples": {
              "application/json": {
                "success": 2,
                "failed": 0,
                "tasks": [
                  {
                    "status": true,
                    "message": "Success",
                    "_id": "634e98098ce07d29474a7e22_example@mile.app_1675224349343"
                  },
                  {
                    "status": true,
                    "message": "Success",
                    "_id": "634e98098ce07d29474a7e22_example@mile.app_1675224349578"
                  }
                ]
              }
            },
            "headers": {}
          },
          "400": {
            "description": "Bad Request",
            "schema":{
              "$ref": "#/definitions/ErrorResponse"
            },
            "examples": {
              "application/json": {
                "status": false,
                "message": "message",
                "failedCode": "lochi-001"
              }
            }
          }
        },
        "security": [
          {
            "AccessToken": [],
            "x-api-key": []
          }
        ]
      }
    }
  },
  "definitions": {
    "postRequestLocHistory": {
      "title": "postRequestLocHistory",
      "example": {
        "email": "example@mile.app",
        "taskId": "634e98098ce69d29474a7e11",
        "speed": 40,
        "distance": 50,
        "duration": 50,
        "lat": "-6.1771046",
        "lon": "106.9240199",
        "createdTime": "2022-10-07 03:00:58",
        "startTime": "2022-10-07 03:00:58",
        "finishTime": "2022-10-07 03:00:58",
        "notes": "Example notes",
        "data": {
          "temperature": 31,
          "anotherKey": "anotherValue"
        }
      },
      "type": "object",
      "properties": {
        "email": {
          "type": "string",
          "description": "Required, User's email assigned to the monitored task. **Example:** `example@mile.app`"
        },
        "taskId": {
          "type": "string",
          "description": "Unique ID to identify the task. **Example:** `634e98098ce69d29474a7e11`"
        },
        "speed": {
          "type": "integer",
          "description": "Vehicle speed in kilometers per hour. **Example:** `40`"
        },
        "distance": {
          "type": "integer",
          "description": "Distance traveled from the previous location. **Example:** `40`"
        },
        "duration": {
          "type": "integer",
          "description": "Time duration spent at this location in milliseconds. **Example:** `50`"
        },
        "lat": {
          "type": "string",
          "description": "Required, Latitude coordinate position or location of any place on Earth's surface. **Example:** `-6.1771046`"
        },
        "lon": {
          "type": "string",
          "description": "Required, Longitude coordinate position or location of any place on Earth's surface. **Example:** `106.9240199`"
        },
        "createdTime": {
          "type": "string",
          "description": "Time at which the location history was created. **Example:** `2022-10-07 03:00:58`"
        },
        "startTime": {
          "type": "string",
          "description": "Time at which the start working was created. Include this payload when starting work. **Example:** `2022-10-07 03:00:58`"
        },
        "finishTime": {
          "type": "string",
          "description": "Time at which the finish working was created. Include this payload when finishing work. **Example:** `2022-10-07 03:00:58`"
        },
        "notes": {
          "type": "string",
          "description": "Field for written records used to capture and retain important information. **Example:** `Example notes`"
        },
        "data": {
          "type": "object",
          "description": "This is a free object that you can fill with any data in object format. **Example:** `{'temperature': 31, 'anotherKey': 'anotherValue'}`"
        }
      },
      "required": [
        "email",
        "lat",
        "lon"
      ]
    },
    "postBulkRequestLocHistory": {
      "title": "postBulkRequestLocHistory",
      "example": {
        "location_histories": [
          {
            "email": "example@mile.app",
            "taskId": "634e98098ce69d29474a7e11",
            "speed": 40,
            "distance": 50,
            "duration": 50,
            "lat": -6.1771046,
            "lon": 106.9240199
          },
          {
            "email": "example@mile.app",
            "taskId": "634e98098ce69d29474a7e11",
            "speed": 40,
            "distance": 50,
            "duration": 50,
            "lat": -6.1771047,
            "lon": 106.92402
          }
        ]
      },
      "type": "object",
      "properties": {
        "location_histories": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/LogHistoryExampleReq"
          }
        }
      },
      "required": [
        "location_histories"
      ]
    },
    "LogHistoryExampleReq": {
      "title": "LogHistoryExampleReq",
      "example": {
        "email": "example@mile.app",
        "taskId": "634e98098ce69d29474a7e11",
        "speed": 40,
        "distance": 50,
        "duration": 50,
        "lat": -6.1771047,
        "lon": 106.92402
      },
      "type": "object",
      "properties": {
        "email": {
          "type": "string",
          "description": "Required, User's email assigned to the monitored task. **Example:** `example@mile.app`"
        },
        "taskId": {
          "type": "string",
          "description": "Unique ID to identify the task. **Example:** `634e98098ce69d29474a7e11`"
        },
        "speed": {
          "type": "integer",
          "description": "Vehicle speed in kilometers per hour. **Example:** `40`"
        },
        "distance": {
          "type": "integer",
          "description": "Distance traveled from the previous location. **Example:** `50`"
        },
        "duration": {
          "type": "integer",
          "description": "Time duration spent at this location in milliseconds. **Example:** `50`"
        },
        "lat": {
          "type": "string",
          "description": "Required, Latitude coordinate position. **Example:** `-6.1771047`"
        },
        "lon": {
          "type": "string",
          "description": "Required, Longitude coordinate position. **Example:** `106.92402`"
        }
      },
      "required": [
        "email",
        "lat",
        "lon"
      ]
    },
    "putRequestLocHistory": {
      "title": "putRequestLocHistory",
      "example": {
        "email": "example@mile.app",
        "lat": -6.934837011379089,
        "lon": 107.74135602107883,
        "speed": 102,
        "createdTime": "2023-07-07 16:00:10",
        "distance": 10,
        "duration": 1,
        "data": {
          "temp": 31
        },
        "taskId": "",
        "time": 1688720650331
      },
      "type": "object",
      "properties": {
        "email": {
          "type": "string",
          "description": "Required, User's email assigned to the monitored task. **Example:** `example@mile.app`"
        },
        "taskId": {
          "type": "string",
          "description": "Unique ID to identify the task. **Example:** `634e98098ce69d29474a7e11`"
        },
        "speed": {
          "type": "integer",
          "description": "Vehicle speed in kilometers per hour. **Example:** `102`"
        },
        "distance": {
          "type": "integer",
          "description": "Distance traveled from the previous location. **Example:** `10`"
        },
        "duration": {
          "type": "integer",
          "description": "Time duration spent at this location in milliseconds. **Example:** `1`"
        },
        "lat": {
          "type": "string",
          "description": "Required, Latitude coordinate position. **Example:** `-6.934837011379089`"
        },
        "lon": {
          "type": "string",
          "description": "Required, Longitude coordinate position. **Example:** `107.74135602107883`"
        }
      },
      "required": [
        "email",
        "lat",
        "lon"
      ]
    },
    "patchRequestLocHistory": {
      "title": "patchRequestLocHistory",
      "example": {
        "email": "example@mile.app",
        "taskId": "634e98098ce69d29474a7e11",
        "speed": 40,
        "distance": 50,
        "duration": 50,
        "lat": -6.1771046,
        "lon": 106.9240199
      },
      "type": "object",
      "properties": {
        "email": {
          "type": "string",
          "description": "Required, User's email assigned to the monitored task. **Example:** `example@mile.app`"
        },
        "taskId": {
          "type": "string",
          "description": "Unique ID to identify the task. **Example:** `634e98098ce69d29474a7e11`"
        },
        "speed": {
          "type": "integer",
          "description": "Vehicle speed in kilometers per hour. **Example:** `40`"
        },
        "distance": {
          "type": "integer",
          "description": "Distance traveled from the previous location. **Example:** `50`"
        },
        "duration": {
          "type": "integer",
          "description": "Time duration spent at this location in milliseconds. **Example:** `50`"
        },
        "lat": {
          "type": "string",
          "description": "Required, Latitude coordinate position. **Example:** `-6.1771046`"
        },
        "lon": {
          "type": "string",
          "description": "Required, Longitude coordinate position. **Example:** `106.9240199`"
        }
      },
      "required": [
        "email",
        "lat",
        "lon"
      ]
    },
    "deleteRequestLocHistory": {
      "title": "deleteRequestLocHistory",
      "example": {
        "force": false
      },
      "type": "object",
      "properties": {
        "force": {
          "type": "boolean",
          "description": "Flag indicating whether to force delete. **Example:** `false`"
        }
      },
      "required": [
        "force"
      ]
    },
    "ApiResponse": {
      "type": "object",
      "properties": {
        "status": {
          "type": "boolean",
          "description": "Indicates whether the request was successful."
        },
        "code": {
          "type": "integer",
          "description": "HTTP status code."
        },
        "message": {
          "type": "string",
          "description": "A message providing additional information about the response."
        },
        "location_history": {
          "$ref": "#/definitions/LocationHistoryResponse"
        }
      }
    },
    "LocationHistoryResponse": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string",
          "description": "User's email assigned to the monitored task."
        },
        "lat": {
          "type": "number",
          "description": "Latitude coordinate position."
        },
        "lon": {
          "type": "number",
          "description": "Longitude coordinate position."
        },
        "speed": {
          "type": "integer",
          "description": "Vehicle speed in kilometers per hour."
        },
        "distance": {
          "type": "integer",
          "description": "Distance traveled from the previous location."
        },
        "duration": {
          "type": "integer",
          "description": "Time duration spent at this location in milliseconds."
        },
        "createdTime": {
          "type": "string",
          "description": "Time at which the location history was created."
        },
        "_id": {
          "type": "string",
          "description": "Unique identifier for the location history entry."
        },
        "taskId": {
          "type": "string",
          "description": "Unique ID to identify the task."
        },
        "time": {
          "type": "integer",
          "description": "A timestamp indicating the time of the location history entry."
        },
        "organizationId": {
          "type": "string",
          "description": "Unique identifier for the organization."
        },
        "updatedBy": {
          "type": "string",
          "description": "Email of the user who last updated the location history entry."
        },
        "createdBy": {
          "type": "string",
          "description": "Email of the user who created the location history entry."
        },
        "updatedTime": {
          "type": "string",
          "description": "Time at which the location history entry was last updated."
        }
      }
    },
    "ErrorResponse": {
      "type": "object",
      "properties": {
        "status": {
          "type": "boolean",
          "description": "Indicates whether the request was successful."
        },
        "message": {
          "type": "string",
          "description": "A message providing additional information about the error."
        }
      },
      "required": ["status", "message"]
    },
    "BulkResponse": {
      "type": "object",
      "properties": {
        "success": {
          "type": "integer",
          "description": "Number of successful operations."
        },
        "failed": {
          "type": "integer",
          "description": "Number of failed operations."
        },
        "location_histories": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/BulkLocationHistoryResponse"
          },
          "description": "Array of responses for each location history entry."
        }
      },
      "required": ["success", "failed", "location_histories"]
    },
    "BulkLocationHistoryResponse": {
      "type": "object",
      "properties": {
        "status": {
          "type": "boolean",
          "description": "Indicates whether the operation was successful."
        },
        "message": {
          "type": "string",
          "description": "A message providing additional information about the operation."
        },
        "_id": {
          "type": "string",
          "description": "Unique identifier for the location history entry."
        },
        "email": {
          "type": "string",
          "description": "User's email assigned to the monitored task."
        }
      },
      "required": ["status", "message", "_id", "email"]
    },
    "RecalculateResponse": {
      "type": "object",
      "properties": {
        "status": {
          "type": "boolean",
          "description": "Indicates whether the recalculation was successful."
        },
        "message": {
          "type": "string",
          "description": "A message providing additional information about the recalculation."
        },
        "data": {
          "$ref": "#/definitions/RecalculateData",
          "description": "Data related to the recalculation process."
        }
      }
    },
    "RecalculateData": {
      "type": "object",
      "properties": {
        "background": {
          "type": "boolean",
          "description": "Indicates whether the recalculation was performed in the background."
        },
        "locationHistory": {
          "$ref": "#/definitions/LocationHistoryResponse",
          "description": "Details of the recalculated location history."
        },
        "payload": {
          "$ref": "#/definitions/RecalculatePayload",
          "description": "Payload containing coordinates and country code used in the recalculation."
        },
        "result": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/RecalculateResult"
          },
          "description": "Array of detailed results for each segment of the location history."
        }
      }
    },
    "RecalculatePayload": {
      "type": "object",
      "properties": {
        "coordinates": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/CoordinatePair"
          },
          "description": "Array of coordinate pairs used in the recalculation."
        },
        "countryCode": {
          "type": "string",
          "description": "Country code associated with the coordinates."
        }
      },
      "required": ["coordinates", "countryCode"]
    },
    "RecalculateResult": {
      "type": "object",
      "properties": {
        "status": {
          "type": "boolean",
          "description": "Indicates whether the recalculation for this segment was successful."
        },
        "message": {
          "type": "string",
          "description": "A message providing additional information about the recalculation result."
        },
        "data": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/SegmentData"
          },
          "description": "Array of distance and time data for each segment."
        }
      },
      "required": ["status", "message", "data"]
    },
    "SegmentData": {
      "type": "object",
      "properties": {
        "distance": {
          "type": "number",
          "description": "Distance for the segment."
        },
        "time": {
          "type": "number",
          "description": "Time taken for the segment."
        }
      },
      "required": ["distance", "time"]
    },
    "CoordinatePair": {
      "type": "object",
      "properties": {
        "coordinateOrigin": {
          "type": "string",
          "description": "The origin coordinates in the format 'latitude,longitude'."
        },
        "coordinateDestination": {
          "type": "string",
          "description": "The destination coordinates in the format 'latitude,longitude'."
        }
      },
      "required": ["coordinateOrigin", "coordinateDestination"]
    },
    "PostRecalculate": {
      "type": "object",
      "properties": {
        "background": {
          "type": "boolean",
          "description": "Indicates whether the operation was performed in the background."
        },
        "locationHistoryId": {
          "type": "string",
          "description": "The ID associated with the location history."
        }
      },
      "required": ["background", "locationHistoryId"]
    }

  },
  "security": []
}