{
    "swagger": "2.0",
    "host": "apiweb.mile.app",
    "basePath": "/api/v3/dashboard",
    "securityDefinitions": {
      "AccessToken": {
        "type": "apiKey",
        "name": "Authorization",
        "in": "header"
      }
    },
    "schemes": [
      "https"
    ],
    "consumes": [
      "application/json"
    ],
    "produces": [
      "application/json"
    ],
    "paths": {
      "/secret/{id}": {
        "get": {
          "summary": "Validate secret ID",
          "tags": [
            "Authentication"
          ],
          "operationId": "validatesecretId",
          "deprecated": false,
          "produces": [
            "application/json"
          ],
          "parameters": [
            {
                "name": "id",
                "in": "path",
                "required": true,
                "type": "string",
                "description": "Unique identifier for the otp session that generated by system.<br>**Example**: `6352736c628401059b37a2e2`"
            }
          ],
          "responses": {
            "200": {
                "description": "Success",
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "description": "Status of response.",
                      "type": "integer"
                    },
                    "message": {
                      "description": "Message of response.",
                      "type": "integer"
                    },
                    "data": {
                      "description": "Details of auth data.",
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "email" : {
                            "description" : "Masked email user login",
                            "type" : "string"
                          }
                        }
                      }
                    }
                  },
                  "example":{
                    "status": true,
                    "message": "success",
                    "data": {
                        "email": "ali***@paket.id"
                    }
                }
                }
              },
              "400": {
                "description": "Bad Request",
                "schema": {
                  "type": "object",
                  "title": "NetworkCreateResponse",
                  "properties": {
                    "status": {
                      "description": "Status of response.",
                      "type": "string"
                    },
                    "message": {
                      "description": "Message of API response.",
                      "type": "string"
                    }
                  }
                },
                "examples": {
                    "application/json": {
                      "status": false,
                      "message": "Failed to create data",
                      "failedCode": "secrt-001"
                    }
                  }
              }
          },
          "security": [
            {
              "AccessToken": []
            }
          ]
        },
        "put": {
            "summary": "Resend OTP code by ID",
            "tags": [
              "Authentication"
            ],
            "operationId": "resendOtpCode",
            "deprecated": false,
            "produces": [
              "application/json"
            ],
            "parameters": [
              {
                  "name": "id",
                  "in": "path",
                  "required": true,
                  "type": "string",
                  "description": "Unique identifier for the otp session that generated by system.<br>**Example**: `6352736c628401059b37a2e2`"
              }
            ],
            "responses": {
              "200": {
                  "description": "Success",
                  "schema": {
                    "type": "object",
                    "properties": {
                      "status": {
                        "description": "Status of response.",
                        "type": "boolean"
                      },
                      "message": {
                        "description": "Message of response.",
                        "type": "string"
                      },
                      "data": {
                        "description": "Details of auth data.",
                        "type": "array",
                        "items": {
                          "type": "object",
                          "properties": {
                            "email" : {
                              "description" : "Masked email user login",
                              "type" : "string"
                            }
                          }
                        }
                      }
                    },
                    "example":{
                      "status": true,
                      "message": "success",
                      "data": {
                          "email": "ali***@paket.id"
                      }
                  }
                  }
                },
                "400": {
                  "description": "Bad Request",
                  "schema": {
                    "type": "object",
                    "title": "NetworkCreateResponse",
                    "properties": {
                      "status": {
                        "description": "Status of response.",
                        "type": "boolean"
                      },
                      "message": {
                        "description": "Message of API response.",
                        "type": "string"
                      }
                    }
                  },
                  "examples": {
                    "application/json": {
                      "status": false,
                      "message": "Failed to login",
                      "failedCode": "secrt-034"
                    }
                  }
                }
            },
            "security": [
              {
                "AccessToken": []
              }
            ]
          }
      },
      "/secret": {
        "post": {
          "summary": "Validate secret OTP",
          "tags": [
            "Authentication"
          ],
          "operationId": "validatesecret",
          "deprecated": false,
          "produces": [
            "application/json"
          ],
          "parameters": [
            {
                "name": "Body",
                "in": "body",
                "required": true,
                "schema": {
                  "$ref": "#/definitions/validate-secret-body"
                }
            }
          ],
          "responses": {
            "200": {
                "description": "Success",
                "schema": {
                  "type": "object",
                  
                  "example": {
                    "token": "eyJ0eXAiOiJKV1Qi...",
                    "expires_in": 31622399,
                    "data": {
                      "_id": "63c63b9e5c29ad437a7cd638",
                      "name": "John Doe",
                      "email": "johndoe@domain.com",
                      "hubId": [
                        "63c63c035c29ad437a7cd63a"
                      ],
                      "organizationId": "63c63b9c5c29ad437a7cd632",
                      "status": "active",
                      "isDeleted": false,
                      "isFieldUser": 0,
                      "roleId": "63c63b9c5c29ad437a7cd633",
                      "activationCode": "84d79ab806972dcec4aa9f66c4b6dc93",
                      "onboardingStep": [],
                      "updatedTime": "2023-02-27T06:37:59+00:00",
                      "createdTime": "2023-01-17T06:09:34+00:00",
                      "avatar": "https://mileroute.sgp1.digitaloceanspaces.com/dev/2023/2/27/johndoe.jpeg",
                      "organization": {
                        "_id": "63c63b9c5c29ad437a7cd632",
                        "user": {
                          "name": "John Doe",
                          "country": "IDN",
                          "phoneNumber": "+62 12345678",
                          "numberOfUsers": "1-50",
                          "industry": "Field Service",
                          "position": "Owner/Director",
                          "email": "johndoe@domain.com",
                          "companyName": "MileApp",
                          "hub": {
                            "name": "Stasiun Bandung",
                            "displayName": "Stasiun Bandung",
                            "address": "Bandung Kota 40113, Indonesia",
                            "lat": "-6.91266",
                            "lng": "107.60791"
                          },
                          "flows": [
                            "62d526290b18b1039408f652",
                            "62d525fe2f12035a550a55e3",
                            "63a561c0fd378bcce9877d2f",
                            "63a561c0fd378bcce9877d30",
                            "62d526540b18b1039408f653",
                            "63a561c0fd378bcce9877d31"
                          ]
                        },
                        "productId": "prod_free",
                        "status": "verified",
                        "curPeriodEndTime": null,
                        "curPeriodStartTime": null,
                        "eligible": true,
                        "updatedTime": "2023-01-19T06:24:47+00:00",
                        "createdTime": "2023-01-17T06:09:32+00:00",
                        "customerId": {
                          "idr": "cus_NBVOcrB6Ksmhvz",
                          "usd": null
                        },
                        "country": {
                          "code": "IDN",
                          "phoneCode": "+62",
                          "name": "Indonesia",
                          "alpha2Code": "ID"
                        }
                      },
                      "role": {
                        "_id": "63c63b9c5c29ad437a7cd633",
                        "name": "owner",
                        "isAdmin": true,
                        "isDefault": false,
                        "isDeleted": false,
                        "permissionList": [
                          "6156d6475320c9679e337eba",
                          "615ac4ab5c3c0b3d3e83dfc1",
                          "615ac4ab5c3c0b3d3e83dfc2",
                          "615ac5175c3c0b3d3e83dfc3",
                          "615ac5185c3c0b3d3e83dfc5",
                          "615ac5185c3c0b3d3e83dfc6",
                          "615ac5185c3c0b3d3e83dfc7",
                          "615ac5195c3c0b3d3e83dfc8",
                          "615ac5195c3c0b3d3e83dfc9",
                          "615ac5625c3c0b3d3e83dfca",
                          "615ac5635c3c0b3d3e83dfcb",
                          "615ac5635c3c0b3d3e83dfcc",
                          "6163b9f723c7545255411653",
                          "6163b9f823c7545255411655",
                          "6163b9f823c7545255411656",
                          "61699635faf2a008e491e117",
                          "61699635faf2a008e491e118",
                          "61699636faf2a008e491e119",
                          "61710b3e83e2af47aa833dfd",
                          "61725da59e28573f25d21433",
                          "619df73f4b17064cfff6d3f1",
                          "619df73f4b17064cfff6d3f2",
                          "619df73f4b17064cfff6d3f3",
                          "61a589a721d8e9691727abca",
                          "61a589a721d8e9691727abcb",
                          "61a589a821d8e9691727abcc",
                          "61a589a821d8e9691727abcd",
                          "61a589a921d8e9691727abcf",
                          "61a589aa21d8e9691727abd0",
                          "61a589aa21d8e9691727abd1",
                          "61a589ab21d8e9691727abd2",
                          "61d3f0a024406248b48614b3",
                          "61d3f0d524406248b48615b9",
                          "61d3f0fe24406248b48616ac",
                          "61d3f12d24406248b48617d9",
                          "61d3f19324406248b4861909",
                          "61d3f1a224406248b4861991",
                          "61d3f1b624406248b48619be",
                          "61d3f24524406248b4861c20",
                          "61d3f25424406248b4861ca1",
                          "622578a0e9afc432da65dac1",
                          "622578a0e9afc432da65dac2",
                          "622578a0e9afc432da65dac3",
                          "622578a0e9afc432da65dac4",
                          "622b338c2edf688a1d57cdaa",
                          "622b33af2edf688a1d57ce21",
                          "622b3e492edf688a1d57f49a",
                          "62554e48475945cff4f7a7de",
                          "6257cc1e475945cff40aea6b",
                          "6257cc1e475945cff40bea1b",
                          "627cb24e62e252387d3bd03d",
                          "627cb24e62e252387d3bd03f",
                          "627dfeadafaf4c30b52e62ad",
                          "627dfeadafaf4c30b52e62af",
                          "62c7eb1203c741efeeb6cc8c",
                          "62c7eb1203c741efeeb6cc8d",
                          "62c7eb1203c741efeeb6cc8e",
                          "62c7eb1203c741efeeb6cc8f",
                          "631025d1267dfb33da11f9dd",
                          "631025d1267dfb33da11f9de"
                        ],
                        "organizationId": "63c63b9c5c29ad437a7cd632",
                        "updatedTime": "2023-03-08T08:48:37.552000Z",
                        "createdTime": "2023-01-17T06:09:32.777000Z",
                        "permissionDetails": [
                          {
                            "permissionName": "view/checkincheckout",
                            "interval": 5,
                            "checkinRadius": 25,
                            "checkoutRadius": 25
                          }
                        ]
                      }
                    },
                    "isHubSet": true
                  }
                }
              },
              "400": {
                "description": "Bad Request",
                "schema": {
                  "type": "object",
                  "title": "NetworkCreateResponse",
                  "properties": {
                    "status": {
                      "description": "Status of response.",
                      "type": "string"
                    },
                    "message": {
                      "description": "Message of API response.",
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "application/json": {
                    "status": false,
                    "message": "Failed to create data",
                    "failedCode": "secrt-001"
                  }
                }
              }
          },
          "security": [
            {
              "AccessToken": []
            }
          ]
        }
      }
      
    },
    "definitions": {
      "default_header": {},
      "validate-secret-body" : {
        "example": {
            "id" : "64df130f23e1a854b5072ba2",
            "secret" : "323277"
        },
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description" : "Unique identifier for the otp session that generated by system. **Example:** `6352736c628401059b37a2e2`"
          },
          "secret": {
            "type": "string",
            "description" : "Unique code that send to user email. **Example:** `6352736c628401059b37a2e2`"
          }
        },
        "required": [
          "resultId"
        ]
      }
    }
  }