{
    "swagger": "2.0",
    "info": {
      "title": "Capacity Constraint",
      "description": "\n\n      Capacity Constraints is a rule that governs the amount of items that can be awarded to a route optimization. Using a capacity constraint, business can be awarded to a preferred vahicle based on volume limitation.\n\n       \n      \n\n      **Below is the detail of each field for data capacity constraint**\n\n      \n| Field | Type | Format | Description |\n\n      |---|---|---|---|\n\n      | _id | <a href='#introduction-format'>string</a> | *24 characters of hexadecimal* | Unique identifier for the capacity constraint<br>that generated by system.<br>**Example**: `6352736c628401059b37a2e2`|\n\n      | organizationId | <a href='#introduction-format'>string</a> | *24 characters of hexadecimal* | The identifier for the organization<br>that generated by system.<br>**Example:** `634e98098ce07d29474a7e22`|\n\n      | capacityConstraint | <a href='#introduction-format'>array of object</a> | Array of Object with format:<br>`[{`<br>`'name':'constraint-name',`<br>`'denominator':'denominator'`<br>`}]` | A list of dynamic capacity types according to user needs. <br>**Example**: <br>`[{`<br>`'name':'weight'`,<br>`'denominator':'Kg'`<br>`}]`|\n\n      \n"
    },
    "host": "apiweb.mile.app",
    "basePath": "/api/v3",
    "securityDefinitions": {
      "AccessToken": {
        "type": "apiKey",
        "name": "Authorization",
        "in": "header"
      }
  
    },
    "schemes": [
      "https"
    ],
    "consumes": [
      "application/json"
    ],
    "produces": [
      "application/json"
    ],
    "paths": {
      "/capacity-constraints": {
        "get": {
          "summary": "Read",
          "tags": [
            "Capacity Constraint"
          ],
          "operationId": "GetCapacityConstraint",
          "deprecated": false,
          "produces": [
            "application/json"
          ],
          "parameters": [
            {
              "name": "limit",
              "in": "query",
              "required": false,
              "type": "string",
              "description": "Limit of configuration result list.<br>**Example:** `10`.<br>**Default:** `20`"
            },
            {
              "name": "page",
              "in": "query",
              "required": false,
              "type": "string",
              "description": "Pagination of configuration result list.<br>**Example:** `2`.<br>**Default:** `0`"
            },
            {
              "name": "sortBy",
              "in": "query",
              "required": false,
              "type": "string",
              "description": "sortBy is used to sort the result-set in ascending or descending order according to selected field. The value of this param is one of available fields on capacity constraint objects.<br>**Default:** `createdTime`"
            },
            {
              "name": "sortOrder",
              "in": "query",
              "required": false,
              "type": "string",
              "description": "sortOrder is to decide ascending or descending order<br>**Example:** `asc` or `desc`.<br>**Default:** `desc`"
            }
          ],
          "responses": {
            "200": {
              "description": "\n  **Below is detail each field for Response API result** \n\n\n              | Field | Type | Description |\n\n              |---|---|---|\n\n              | status | <a href='#introduction-format'>boolean</a> | Status of response |\n\n              | data | <a href='#introduction-format'>array of object</a> | multiple object of capacity constraint in array |\n\n              ",
              "examples": {
                "application/json": {
                  "status": true,
                  "data": [
                    {
                      "_id": "61c2fbaaf27b374e8913fe79",
                      "name": "Configuration Default",
                      "capacityConstraint": [
                        {
                          "name": "weight",
                          "denominator": "Kg"
                        }
                      ],
                      "organizationId": "61c2fbaaf27b374e8913fe72",
                      "isDeleted": false,
                      "updatedTime": "1970-01-25T20:31:23.647000Z",
                      "createdTime": "1970-01-25T20:31:23.647000Z"
                    }
                  ]
                }
              },
              "headers": {
                "$ref": "#/definitions/default_header"
              }
            },
            "400": {
              "description": "Bad Request",
              "examples": {
                "application/json": {
                  "status": false,
                  "message": "message",
                  "failedCode": "capac-001"
                }
              },
              "headers": {
                "$ref": "#/definitions/default_header"
              }
            }
          },
          "security": [
            {
              "AccessToken": [ ]
            }
          ]
        }
      },
      "/capacity-constraint": {
        "get": {
          "summary": "Read single data",
          "tags": [
            "Capacity Constraint"
          ],
          "operationId": "GetCapacityConstraintSingleData",
          "deprecated": false,
          "produces": [
            "application/json"
          ],
          "parameters": [],
          "responses": {
            "200": {
              "description": "Success",
              "schema" : {
                "type" : "object",
                "properties" : {
                  "status": {
                    "description": "Status of response.",
                    "type": "boolean"
                  },
                  "message": {
                    "description": "Message of response.",
                    "type": "string"
                  },
                  "data": {
                    "description": "Object of details capacity constraint data.",
                    "type": "object"
                  }
                },
                "example" : {
                  "status": true,
                  "message" : "Success",
                  "data": {
                    "_id": "61c2fbaaf27b374e8913fe79",
                    "name": "Configuration Default",
                    "capacityConstraint": [
                      {
                        "name": "weight",
                        "denominator": "Kg"
                      }
                    ],
                    "organizationId": "61c2fbaaf27b374e8913fe72",
                    "isDeleted": false,
                    "updatedTime": "1970-01-25T20:31:23.647000Z",
                    "createdTime": "1970-01-25T20:31:23.647000Z"
                  }
                }
              }
            },
            "400": {
              "description": "Bad Request",
              "examples": {
                "application/json": {
                  "status": false,
                  "message": "message"
                }
              }
            }
          },
          "security": [
            {
              "AccessToken": [ ]
            }
          ]
        }
      },
      "/capacity-constraint/{capacityconstraint_id}": {
        "get": {
          "summary": "Read by ID",
          "tags": [
            "Capacity Constraint"
          ],
          "operationId": "CapacityConstraints",
          "deprecated": false,
          "produces": [
            "application/json"
          ],
          "parameters": [
            {
              "name": "capacityconstraint_id",
              "in": "path",
              "required": true,
              "type": "string",
              "description": "Unique identifier for the capacity constraint that generated by system.<br>**Example**: `62034a3db50b000091006086`"
            }
          ],
          "responses": {
            "200": {
              "description": "\n  **Below is detail each field for Response API result** \n\n\n              | Field | Type | Description |\n\n              |---|---|---|\n\n              | status | <a href='#introduction-format'>boolean</a> | Status of response |\n\n              | data | <a href='#introduction-format'>object</a> | Detail of capacity constraint object |\n\n              ",
              "examples": {
                "application/json": {
                  "status": true,
                  "data": {
                    "_id": "62034a3db50b000091006086",
                    "capacityConstraint": [
                      {
                        "name": "weight",
                        "denominator": "Kg"
                      }
                    ],
                    "organizationId": "61c2fbaaf27b374e8913fe72",
                    "isDeleted": false,
                    "updatedTime": "1970-01-25T20:31:23.647000Z",
                    "createdTime": "1970-01-25T20:31:23.647000Z"
                  }
                }
              },
              "headers": {
                "$ref": "#/definitions/default_header"
              }
            },
            "404": {
              "description": "Not Found",
              "examples": {
                "application/json": {
                  "status": false,
                  "data": [],
                  "statusCode": 404,
                  "message": "data not found",
                  "failedCode": "capac-033"
                }
              },
              "headers": {
                "$ref": "#/definitions/default_header"
              }
            }
          },
          "security": [
            {
              "AccessToken": [ ]
            }
          ]
        },
        "put": {
          "summary": "Update",
          "tags": [
            "Capacity Constraint"
          ],
          "operationId": "PutCapacityConstraint",
          "deprecated": false,
          "produces": [
            "application/json"
          ],
          "parameters": [
            {
              "name": "capacityconstraint_id",
              "in": "path",
              "required": true,
              "type": "string",
              "description": "Unique identifier for the capacity constraint that generated by system.<br>**Example**: `62034a3db50b000091006086`"
            },
            {
              "name": "Body",
              "in": "body",
              "required": true,
              "description": "\n\n              **Below is the detail of each field for Body API Configuration**\n\n            \n| Field | Description | Required |\n\n              |---|---|---|\n\n              \n",
              "schema": {
                "$ref": "#/definitions/CapacityConstraintRequestPost"
              }
            }
          ],
          "responses": {
            "200": {
              "description": "\n  **Below is detail each field for Response API result** \n\n\n              | Field | Type | Description |\n\n              |---|---|---|\n\n              | status | <a href='#introduction-format'>boolean</a> | Status of response |\n\n              | data | <a href='#introduction-format'>object</a> | Detail of capacity constraint object |\n\n              ",
              "examples": {
                "application/json": {
                  "status": true,
                  "data": {
                    "_id": "62034a3db50b000091006086",
                    "name": "Default",
                    "capacityConstraint": [
                      {
                        "name": "weight",
                        "denominator": "Kg"
                      }
                    ],
                    "organizationId": "61c2fbaaf27b374e8913fe72",
                    "isDeleted": false,
                    "updatedTime": "1970-01-25T20:31:23.647000Z",
                    "createdTime": "1970-01-25T20:31:23.647000Z"
                  }
                }
              },
              "headers": {
                "$ref": "#/definitions/default_header"
              }
            },
            "400": {
              "description": "Bad Request",
              "examples": {
                "application/json": {
                  "status": false,
                  "message": "message",
                  "failedCode": "capac-001"
                }
              },
              "headers": {
                "$ref": "#/definitions/default_header"
              }
            }
          },
          "security": [
            {
              "AccessToken": [ ]
            }
          ]
        },
        "delete": {
          "summary": "Delete",
          "tags": [
            "Capacity Constraint"
          ],
          "operationId": "DeleteCapacityConstraint",
          "deprecated": false,
          "produces": [
            "application/json"
          ],
          "parameters": [
            {
              "name": "capacityconstraint_id",
              "in": "path",
              "required": true,
              "type": "string",
              "description": "Unique identifier for the capacity constraint that generated by system.<br>**Example**: `62034a3db50b000091006086`"
            }
          ],
          "responses": {
            "200": {
              "description": "\n  **Below is detail each field for Response API result** \n\n\n              | Field | Type | Description |\n\n              |---|---|---|\n\n              | status | <a href='#introduction-format'>boolean</a> | Status of response |\n\n              | data | <a href='#introduction-format'>object</a> | Detail of capacity constraint object |\n\n              ",
              "examples": {
                "application/json": {
                  "status": true,
                  "data": {
                    "_id": "62034a3db50b000091006086",
                    "capacityConstraint": [
                      {
                        "name": "weight",
                        "denominator": "Kg"
                      }
                    ],
                    "isDeleted": true,
                    "updatedTime": "1970-01-25T20:31:23.647000Z",
                    "createdTime": "1970-01-25T20:31:23.647000Z"
                  }
                }
              },
              "headers": {
                "$ref": "#/definitions/default_header"
              }
            },
            "404": {
              "description": "Not Found",
              "examples": {
                "application/json": {
                  "status": false,
                  "data": [],
                  "statusCode": 404,
                  "message": "data not found",
                  "failedCode": "capac-033"
                }
              },
              "headers": {
                "$ref": "#/definitions/default_header"
              }
            }
          },
          "security": [
            {
              "AccessToken": [ ]
            }
          ]
        }
  
      }
  
  
    },
    "definitions": {
      "default_header": {},
      "Configurations": {
        "title": "Configurations",
        "example": {
          "status": true,
          "data": {
            "_id": "62034a3db50b000091006086",
            "name": "Configuration Default",
            "capacityConstraint": [
              {
                "name": "weight",
                "denominator": "Kg"
              }
            ],
            "multitrip": false,
            "returnToBase": false,
            "useAllVehicle": false,
            "clustering": false,
            "autoSpeed": false,
            "defaultSpeed": 15,
            "defaultVisitTime": 10,
            "organizationId": "61c2fbaaf27b374e8913fe72",
            "isDeleted": true,
            "updatedTime": "1970-01-25T20:31:23.647000Z",
            "createdTime": "1970-01-25T20:31:23.647000Z"
          }
        },
        "type": "object",
        "properties": {
          "status": {
            "type": "boolean"
          },
          "data": {
            "$ref": "#/definitions/Data18"
          }
        },
        "required": [
          "status",
          "data"
        ]
      },
      "ConfigurationsRequest": {
        "title": "ConfigurationsRequest",
        "example": {
          "name": "Default",
          "capacityConstraint": [
            {
              "name": "weight",
              "denominator": "Kg"
            }
          ],
          "defaultSpeed": 30,
          "defaultVisitTime": 10,
          "autoSpeed": false,
          "multitrip": false,
          "returnToBase": false,
          "useAllVehicle": false,
          "clustering": false
        },
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "capacityConstraint": {
            "type": "array",
            "items": {
              "$ref": "#/definitions/CapacityConstraint"
            }
          },
          "defaultVisitTime": {
            "type": "integer",
            "format": "int32"
          },
          "defaultSpeed": {
            "type": "integer",
            "format": "int32"
          },
          "multitrip": {
            "type": "boolean"
          },
          "returnToBase": {
            "type": "boolean"
          },
          "useAllVehicle": {
            "type": "boolean"
          },
          "autoSpeed": {
            "type": "boolean"
          },
          "clustering": {
            "type": "boolean"
          }
        },
        "required": [
          "name",
          "capacityConstraint",
          "returnToBase",
          "useAllVehicle",
          "autoSpeed",
          "defaultSpeed",
          "defaultVisitTime",
          "multitrip"
        ]
      },
      "Configurations1": {
        "title": "Configurations1",
        "example": {
          "_id": "62034a3db50b000091006086",
          "name": "Configuration Default",
          "capacityConstraint": [
            {
              "name": "weight",
              "denominator": "Kg"
            }
          ],
          "multitrip": false,
          "returnToBase": false,
          "useAllVehicle": false,
          "clustering": false,
          "autoSpeed": false,
          "defaultSpeed": 15,
          "defaultVisitTime": 10,
          "organizationId": "61c2fbaaf27b374e8913fe72",
          "isDeleted": false,
          "updatedTime": "1970-01-25T20:31:23.647000Z",
          "createdTime": "1970-01-25T20:31:23.647000Z"
        },
        "type": "object",
        "properties": {
          "_id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "capacityConstraint": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "multitrip": {
            "type": "boolean"
          },
          "returnToBase": {
            "type": "boolean"
          },
          "useAllVehicle": {
            "type": "boolean"
          },
          "clustering": {
            "type": "boolean"
          },
          "autoSpeed": {
            "type": "boolean"
          },
          "organizationId": {
            "type": "string"
          },
          "defaultVisitTime": {
            "type": "integer",
            "format": "int32"
          },
          "defaultSpeed": {
            "type": "integer",
            "format": "int32"
          },
          "isDeleted": {
            "type": "boolean"
          },
          "updatedTime": {
            "type": "string"
          },
          "createdTime": {
            "type": "string"
          }
        },
        "required": [
          "_id",
          "name",
          "capacityConstraint",
          "multitrip",
          "returnToBase",
          "useAllVehicle",
          "clustering",
          "autoSpeed",
          "defaultSpeed",
          "defaultVisitTime",
          "organizationId",
          "isDeleted",
          "updatedTime",
          "createdTime"
        ]
      },
      "CapacityConstraintRequestPost": {
        "title": "CapacityConstraintRequestPost",
        "example": {
          "capacityConstraint": [
            {
              "name": "weight",
              "denominator": "Kg"
            }
          ]
        },
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "capacityConstraint": {
            "type": "array",
            "items": {
              "$ref": "#/definitions/CapacityConstraint"
            }
          },
          "defaultVisitTime": {
            "type": "integer",
            "format": "int32"
          },
          "defaultSpeed": {
            "type": "integer",
            "format": "int32"
          },
          "multitrip": {
            "type": "boolean"
          },
          "returnToBase": {
            "type": "boolean"
          },
          "useAllVehicle": {
            "type": "boolean"
          },
          "autoSpeed": {
            "type": "boolean"
          },
          "clustering": {
            "type": "boolean"
          }
        },
        "required": [
          "name",
          "capacityConstraint",
          "defaultVisitTime",
          "defaultSpeed",
          "multitrip",
          "returnToBase",
          "useAllVehicle",
          "autoSpeed",
          "clustering"
        ]
      },
      "Configurations2": {
        "title": "Configurations2",
        "example": {
          "data": {
            "name": "Configuration Default",
            "capacityConstraint": [
              {
                "name": "weight",
                "denominator": "Kg"
              }
            ],
            "defaultSpeed": 15,
            "defaultVisitTime": 10,
            "multitrip": false,
            "returnToBase": false,
            "useAllVehicle": false,
            "clustering": false,
            "autoSpeed": false,
            "organizationId": "61c2fbaaf27b374e8913fe72",
            "isDeleted": false,
            "updatedTime": "1970-01-25T20:31:23.647000Z",
            "createdTime": "1970-01-25T20:31:23.647000Z",
            "_id": "62034a3db50b000091006086"
          },
          "status": true
        },
        "type": "object",
        "properties": {
          "data": {
            "$ref": "#/definitions/Data19"
          },
          "status": {
            "type": "boolean"
          }
        },
        "required": [
          "data",
          "status"
        ]
      },
      "Data18": {
        "title": "Data18",
        "example": {
          "_id": "62034a3db50b000091006086",
          "name": "Configuration Default",
          "capacityConstraint": [
            {
              "name": "weight",
              "denominator": "Kg"
            }
          ],
          "defaultSpeed": 15,
          "defaultVisitTime": 10,
          "multitrip": false,
          "returnToBase": false,
          "useAllVehicle": false,
          "clustering": false,
          "autoSpeed": false,
          "organizationId": "61c2fbaaf27b374e8913fe72",
          "isDeleted": true,
          "updatedTime": "1970-01-25T20:31:23.647000Z",
          "createdTime": "1970-01-25T20:31:23.647000Z"
        },
        "type": "object",
        "properties": {
          "_id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "capacityConstraint": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "multitrip": {
            "type": "boolean"
          },
          "returnToBase": {
            "type": "boolean"
          },
          "useAllVehicle": {
            "type": "boolean"
          },
          "clustering": {
            "type": "boolean"
          },
          "autoSpeed": {
            "type": "boolean"
          },
          "organizationId": {
            "type": "string"
          },
          "isDeleted": {
            "type": "boolean"
          },
          "updatedTime": {
            "type": "string"
          },
          "createdTime": {
            "type": "string"
          },
          "defaultVisitTime": {
            "type": "integer",
            "format": "int32"
          },
          "defaultSpeed": {
            "type": "integer",
            "format": "int32"
          }
        },
        "required": [
          "_id",
          "name",
          "capacityConstraint",
          "multitrip",
          "returnToBase",
          "useAllVehicle",
          "clustering",
          "autoSpeed",
          "defaultSpeed",
          "defaultVisitTime",
          "organizationId",
          "isDeleted",
          "status",
          "updatedTime",
          "createdTime"
        ]
      },
      "CapacityConstraint": {
        "title": "CapacityConstraint",
        "example": {
          "name": "weight",
          "denominator": "Kg"
        },
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "denominator": {
            "type": "string"
          }
        },
        "required": [
          "name",
          "denominator"
        ]
      },
      "Data19": {
        "title": "Data19",
        "example": {
          "name": "Configuration Default",
          "capacityConstraint": [
            {
              "name": "weight",
              "denominator": "Kg"
            }
          ],
          "multitrip": false,
          "returnToBase": false,
          "useAllVehicle": false,
          "clustering": false,
          "autoSpeed": false,
          "defaultSpeed": 15,
          "defaultVisitTime": 10,
          "organizationId": "61c2fbaaf27b374e8913fe72",
          "isDeleted": false,
          "updatedTime": "1970-01-25T20:31:23.647000Z",
          "createdTime": "1970-01-25T20:31:23.647000Z",
          "_id": "62034a3db50b000091006086"
        },
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "capacityConstraint": {
            "type": "array",
            "items": {
              "$ref": "#/definitions/CapacityConstraint"
            }
          },
          "multitrip": {
            "type": "boolean"
          },
          "returnToBase": {
            "type": "boolean"
          },
          "useAllVehicle": {
            "type": "boolean"
          },
          "clustering": {
            "type": "boolean"
          },
          "autoSpeed": {
            "type": "boolean"
          },
          "organizationId": {
            "type": "string"
          },
          "isDeleted": {
            "type": "boolean"
          },
          "updatedTime": {
            "type": "string"
          },
          "createdTime": {
            "type": "string"
          },
          "_id": {
            "type": "string"
          },
          "defaultVisitTime": {
            "type": "integer",
            "format": "int32"
          },
          "defaultSpeed": {
            "type": "integer",
            "format": "int32"
          }
        },
        "required": [
          "name",
          "capacityConstraint",
          "multitrip",
          "returnToBase",
          "useAllVehicle",
          "clustering",
          "autoSpeed",
          "defaultSpeed",
          "defaultVisitTime",
          "organizationId",
          "isDeleted",
          "updatedTime",
          "createdTime",
          "_id"
        ]
      },
      "Configurations3": {
        "title": "Configurations3",
        "type": "object",
        "properties": {
          "data": {
            "type": "array",
            "items": {
              "$ref": "#/definitions/Data20"
            }
          },
          "status": {
            "type": "boolean"
          }
        },
        "required": [
          "data",
          "status"
        ]
      },
      "Data20": {
        "title": "Data20",
        "example": {
          "_id": "61c2fbaaf27b374e8913fe79",
          "name": "Configuration Default",
          "capacityConstraint": [
            {
              "name": "weight",
              "denominator": "Kg"
            }
          ],
          "returnToBase": false,
          "useAllVehicle": false,
          "multitrip": false,
          "clustering": false,
          "autoSpeed": false,
          "defaultSpeed": 15,
          "defaultVisitTime": 10,
          "organizationId": "61c2fbaaf27b374e8913fe72",
          "isDeleted": false,
          "updatedTime": "1970-01-25T20:31:23.647000Z",
          "createdTime": "1970-01-25T20:31:23.647000Z"
        },
        "type": "object",
        "properties": {
          "_id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "capacityConstraint": {
            "example": [
              {
                "name": "weight",
                "denominator": "Kg"
              }
            ],
            "type": "array",
            "items": {
              "$ref": "#/definitions/CapacityConstraint4"
            }
          },
          "returnToBase": {
            "type": "boolean"
          },
          "useAllVehicle": {
            "type": "boolean"
          },
          "multitrip": {
            "type": "boolean"
          },
          "autoSpeed": {
            "type": "boolean"
          },
          "organizationId": {
            "type": "string"
          },
          "isDeleted": {
            "type": "boolean"
          },
          "clustering": {
            "type": "boolean"
          },
          "updatedTime": {
            "type": "string"
          },
          "createdTime": {
            "type": "string"
          },
          "defaultVisitTime": {
            "type": "integer",
            "format": "int32"
          },
          "defaultSpeed": {
            "type": "integer",
            "format": "int32"
          }
        },
        "required": [
          "_id",
          "name",
          "capacityConstraint",
          "returnToBase",
          "useAllVehicle",
          "multitrip",
          "autoSpeed",
          "defaultSpeed",
          "defaultVisitTime",
          "organizationId",
          "isDeleted",
          "clustering",
          "updatedTime",
          "createdTime"
        ]
      },
      "CapacityConstraint4": {
        "title": "CapacityConstraint4",
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "denominator": {
            "type": "string"
          }
        }
      }
    }
  }